Character limit set, history design issues and other design issues fixed
nearcomponents/nft-app-frontend pull request #182
Opened 2022-01-08 01:27 UTC by niravpd8000

2022-01-08 04:21 UTC, biswanathsahoo requested changes

2022-01-08 04:21 UTC, biswanathsahoo commented on src/Components/Dashboard/CreateNFT/createNft.js
> +                  onPaste={(event => inputEvent({ target: {name: "title", value: event.clipboardData.getData('Text').substring(0, 60)}}))}
Please define this 60 in a constant

2022-01-08 04:21 UTC, biswanathsahoo commented on src/Components/Dashboard/CreateNFT/createNft.js
> +                  onPaste={(event => inputEvent({ target: {name: "description", value: event.clipboardData.getData('Text').substring(0, 100)}}))}
Also, put this 100 value in a constant

2022-01-08 04:21 UTC, biswanathsahoo commented on src/layout/DetailRoute.js
>                        )}
Please move these conditional code to a separate component as it being used in other component as well

2022-01-10 07:21 UTC, sparkyrider commented
@niravpd8000 any updates on this? This is pending merge

2022-01-10 19:39 UTC, closed without merging