Batch Contact loading
nearcomponents/nft-app-frontend pull request #239
Opened 2022-01-12 03:35 UTC by alecdev105

2022-01-12 07:58 UTC, biswanathsahoo requested changes

2022-01-12 07:58 UTC, biswanathsahoo commented on src/common/components/ContactPopup.js
> +import useInfiniteScroll from 'react-infinite-scroll-hook';
Build is failing because of this library. Please check

2022-01-12 23:05 UTC, alecdev105 commented
@biswanathsahoo Please check this and merge

2022-01-13 02:08 UTC, biswanathsahoo requested changes
Contacts are not appearing after importing from Google, I can see in the Network log it's coming from the API, but in the UI it's not appearing. Please check

2022-01-25 17:30 UTC, closed without merging