Nftrwp 136 change search current contacts text
nearcomponents/nft-app-frontend pull request #245
Opened 2022-01-12 10:38 UTC by Rajibshrestha59

2022-01-12 12:26 UTC, biswanathsahoo requested changes
Please resolve the conflict

2022-01-13 04:14 UTC, Rajibshrestha59 commented
> Please resolve the conflict

Please check now @biswanathsahoo

2022-01-13 04:40 UTC, biswanathsahoo requested changes
Validation is not working as expected.
Please check these points 
- On manual contact form either phone number or email is mandatory
- On open the popup add focus on the first name input field
- Add enter key event on each input field which will submit the form
- First name and last name are optional, but if someone is providing ten only we have to validate
-  On closing the popup reset the search box and show all the contact(Now it's resetting but now showing all the contacts)

2022-01-13 05:58 UTC, biswanathsahoo requested changes

2022-01-13 05:58 UTC, biswanathsahoo commented on src/common/components/ManualContactPopup.js
> +                    validateFirstName(event)}}}
Here enable the enter key event and don't validate the first name on key press

2022-01-13 05:58 UTC, biswanathsahoo commented on src/common/components/ManualContactPopup.js
> +                    validateLastName(event)}}}
Here also, enable the enter key event and don't validate the last name on key press

2022-01-13 09:43 UTC, biswanathsahoo approved these changes

2022-01-13 09:44 UTC, merged