marco/feature-NFTRWP-189
nearcomponents/nft-app-frontend pull request #274
Opened 2022-01-18 20:47 UTC by marco-calderon-primelab

- Added new property for ContactPopup component for showing a loading when gift is being sent.
- Added new state on sendNft component to enable showing of the loader. Only will show when request is being sent properly to the back end.

Evidence attached:

![image](https://user-images.githubusercontent.com/97699085/150016025-2b7aa3d0-cc06-45f6-9853-839cf32ddf61.png)

2022-01-19 10:06 UTC, biswanathsahoo requested changes
Please do a rebase with dev branch and resolve the conflict.

2022-01-19 10:06 UTC, biswanathsahoo commented on src/Components/Dashboard/SendNFT/sendNft.module.css
> -  margin-left: 20px;
Do this change in sendNft.module.scss file

2022-01-19 17:07 UTC, marco-calderon-primelab commented
Hi @biswanathsahoo please review the changes on this branch, make the required adjustments.

2022-01-20 06:40 UTC, biswanathsahoo commented
@marco-calderon-primelab Your changes breaking the import contact flow. After importing contact, it is displaying all the contacts in a list but the Gift NFT button is not appearing. Please check the flow once.

2022-01-25 17:30 UTC, closed without merging