LP23 - Prime lab text and logo updated
nearcomponents/nft-app-frontend pull request #335
Opened 2022-01-23 17:06 UTC by syed-primelab

2022-01-23 18:10 UTC, biswanathsahoo requested changes

2022-01-23 18:10 UTC, biswanathsahoo commented on src/Components/Home/index.jsx
> +          <img src={Logo} width="200" className={styles.logo} alt="Brand Logo" />
Can you please put the width in logo class name so that it will be easy to manage the size in different devices

2022-01-23 18:11 UTC, biswanathsahoo commented on src/Components/Home/index.jsx
> +          <img src={Logo} width="200" className={styles.logo} alt="Brand Logo" />
Also, please check the logo mobile version

2022-01-24 01:59 UTC, syed-primelab commented on src/Components/Home/index.jsx
> +          <img src={Logo} width="200" className={styles.logo} alt="Brand Logo" />
I checked the size in mobile version and it was fine. But let me put this width in class

2022-01-24 05:13 UTC, biswanathsahoo approved these changes

2022-01-24 05:13 UTC, merged