Lp 24 form web mobile new issue
nearcomponents/nft-app-frontend pull request #341
Opened 2022-01-24 11:05 UTC by fimak

If user is logged in he will be redirected to `/` if he will try to open '/home' or /signup/ or '/signin'

2022-01-24 12:49 UTC, biswanathsahoo requested changes

2022-01-24 12:49 UTC, biswanathsahoo commented on src/Components/SignUp/CreateAnAccount/CreateAnAccount.jsx
> +  useRedirectIfUserLoggedIn();
@fimak This component is being used to add new wallet for the logged in user. So for now let's not add the restriction on this page.

2022-01-24 19:50 UTC, idougwarner commented on src/Components/SignUp/CreateAnAccount/CreateAnAccount.jsx
> +  useRedirectIfUserLoggedIn();
@fimak I think we could replace the current route with the to route on the following pages. check this API reference - https://reactrouter.com/docs/en/v6/api#usenavigate

- when navigating from /signup page to /signup/create-account page
- when navigating from /signup/create-account page page to / page
- when navigating from /signin page to /signin/authentication/idougwarnerdev page
- when navigating from /signin/authentication/idougwarnerdev page to / page

then the user will be taken straight to the home page if the user clicks the go back browser button.

let's remove "Get Started" button and "Launch" buttons on the home page if the user session exists. Instead, let's put "Dashboard" button in the same location as the Launch button

2022-01-24 19:50 UTC, idougwarner commented on src/Components/SignUp/CreateAnAccount/CreateAnAccount.jsx
> +  useRedirectIfUserLoggedIn();
@biswanathsahoo thought?

2022-01-24 20:08 UTC, biswanathsahoo commented on src/Components/SignUp/CreateAnAccount/CreateAnAccount.jsx
> +  useRedirectIfUserLoggedIn();
Yes, this will be great

2022-01-25 04:34 UTC, idougwarner commented on src/Components/SignUp/CreateAnAccount/CreateAnAccount.jsx
> +  useRedirectIfUserLoggedIn();
@fimak can you give me an update on this PR?

2022-01-25 05:02 UTC, fimak commented on src/Components/SignUp/CreateAnAccount/CreateAnAccount.jsx
> +  useRedirectIfUserLoggedIn();
just a few minutes please

2022-01-25 06:52 UTC, sparkyrider commented on src/Components/SignUp/CreateAnAccount/CreateAnAccount.jsx
> +  useRedirectIfUserLoggedIn();
@fimak is this one resolved?

2022-01-25 08:30 UTC, biswanathsahoo requested changes
@fimak Everything looks good except the below scenario 
If the user going to /signup/ page the it is redirecting to home page but if the user going to  /signup page then it is redirecting to /signup/create-account. This is because of the trailing slash at the end of the url slug. So consider   /signup/ is same as /signup

2022-01-25 08:42 UTC, fimak commented
> @fimak Everything looks good except the below scenario If the user going to /signup/ page the it is redirecting to home page but if the user going to /signup page then it is redirecting to /signup/create-account. This is because of the trailing slash at the end of the url slug. So consider /signup/ is same as /signup

Fixed

2022-01-25 08:47 UTC, fimak commented on src/Components/SignUp/CreateAnAccount/CreateAnAccount.jsx
> +  useRedirectIfUserLoggedIn();
@sparkyrider 
Yes

2022-01-25 09:35 UTC, biswanathsahoo approved these changes

2022-01-25 09:43 UTC, merged