Fix transaction list missing data
nearcomponents/nft-app-frontend pull request #398
Opened 2022-01-27 13:24 UTC by firmansyaho

- Filtered out `create_nft_series`  transaction types
- Defined `gift` transaction types data model

2022-01-27 14:21 UTC, idougwarner requested changes

2022-01-27 14:21 UTC, idougwarner commented on src/Components/Dashboard/Transactions/Transaction.js
> +      case 'gift':
@firmansyaho what's the difference between 'gift' and 'unclaimed' type?

2022-01-27 14:21 UTC, idougwarner commented on src/Components/Dashboard/Transactions/TransactionHistory.js
> +    transactions = transactions.filter((item) => item.type !== "create_nft_series");
I would rather filter out transactions by a certain set of types that we're showing in the transactions list. can you check RecenTransactions.jsx?

2022-01-27 18:33 UTC, firmansyaho commented on src/Components/Dashboard/Transactions/Transaction.js
> +      case 'gift':
@idougwarner don't really sure, can't reproduce this gift right now. But it has some of them on my account. Did we don't including this gift type @idougwarner ?

Also all of them this history below,, is a "gift" type
![image](https://user-images.githubusercontent.com/97716187/151421715-6ccd78e3-bf85-4303-a661-6e888e023b50.png)

also was referencing the "gift" nft type looks with[ this](https://builds-org.slack.com/archives/C02V0S4D1D2/p1643167780223300)

2022-01-27 18:35 UTC, firmansyaho commented on src/Components/Dashboard/Transactions/TransactionHistory.js
> +    transactions = transactions.filter((item) => item.type !== "create_nft_series");
Okay will adjusted that. Did we still want to including the "gift" type @idougwarner ?

2022-01-27 18:37 UTC, idougwarner commented on src/Components/Dashboard/Transactions/Transaction.js
> +      case 'gift':
I can no longer find out the gift type. can you ask Prashanth about this?

2022-01-28 12:16 UTC, firmansyaho commented on src/Components/Dashboard/Transactions/Transaction.js
> +      case 'gift':
@idougwarner okay will asked Prashanth

2022-01-28 14:43 UTC, idougwarner approved these changes
Good job

2022-01-28 15:21 UTC, biswanathsahoo requested changes

2022-01-28 15:21 UTC, biswanathsahoo commented on src/Components/Dashboard/Transactions/Transaction.js
> +                : data.counterparty?.[0]?.full_name}
This will not show the name or email if we're sending to a phone number so Instead of full name let's use phone as full_name is optional. Either email or phone number is mandatory.

2022-01-28 15:44 UTC, firmansyaho commented on src/Components/Dashboard/Transactions/Transaction.js
> +                : data.counterparty?.[0]?.full_name}
@biswanathsahoo you are right. 
Done

2022-01-28 16:32 UTC, biswanathsahoo approved these changes

2022-01-28 16:33 UTC, merged