LP-99 - NFT Card image/text spacing fixed
nearcomponents/nft-app-frontend pull request #405
Opened 2022-01-28 03:21 UTC by syed-primelab

2022-01-28 06:09 UTC, biswanathsahoo requested changes

2022-01-28 06:09 UTC, biswanathsahoo commented on src/Components/Dashboard/Home/MyNft.jsx
> +                          )}
Can we create a common component for this as this is being used in multiple places. And please add css in css file instead of inline css

2022-01-28 18:10 UTC, syed-primelab commented
@biswanathsahoo 
Created separate component for card and used in My NFTs section as well.

Now a developer can use this anywhere else. In case of sending NFT little cutomisation will be required as there should be a selection button as well. This will be done in separate PR if ticker created against that.

2022-01-28 19:36 UTC, biswanathsahoo requested changes

2022-01-28 19:36 UTC, biswanathsahoo commented on src/Components/NFT/Card/Card.jsx
> +        <h2 className={styles.text__ellipsis}>{data?.title}</h2>
can you please add title attribute here

2022-01-28 19:36 UTC, biswanathsahoo commented on src/Components/NFT/Card/Card.jsx
> +        <p className={styles.text__ellipsis}>{data?.nft_id}</p>
Here also add the title attribute

2022-01-29 02:14 UTC, syed-primelab commented on src/Components/NFT/Card/Card.jsx
> +        <h2 className={styles.text__ellipsis}>{data?.title}</h2>
Title attribute? Sorry, I don't get it.

2022-01-29 06:37 UTC, biswanathsahoo commented on src/Components/NFT/Card/Card.jsx
> +        <h2 className={styles.text__ellipsis}>{data?.title}</h2>
@syed-primelab as we added the `text-overflow:ellipsis` so it will not show all the text, so for better user experience we can use title attribute or tooltip to show the full text.

2022-01-31 03:15 UTC, syed-primelab commented on src/Components/NFT/Card/Card.jsx
> +        <h2 className={styles.text__ellipsis}>{data?.title}</h2>
@biswanathsahoo added.

2022-01-31 03:15 UTC, syed-primelab commented on src/Components/NFT/Card/Card.jsx
> +        <p className={styles.text__ellipsis}>{data?.nft_id}</p>
@biswanathsahoo added.

2022-01-31 04:27 UTC, biswanathsahoo approved these changes

2022-01-31 04:27 UTC, merged