moble responsive view done
nearcomponents/nft-app-frontend pull request #421
Opened 2022-01-29 15:11 UTC by rajibshresthaprime

2022-01-29 15:44 UTC, biswanathsahoo requested changes
Also, there is some issue in contact list popup and recent transaction component

2022-01-29 15:44 UTC, biswanathsahoo commented on src/Components/Dashboard/SendNFT/sendNft.module.css
> +  word-break: break-all;
Please use  text-overflow: ellipsis; instead breaking the word

2022-01-29 15:45 UTC, rajibshresthaprime commented on src/Components/Dashboard/SendNFT/sendNft.module.css
> +  word-break: break-all;
there's already that property used

2022-01-31 04:30 UTC, biswanathsahoo approved these changes

2022-01-31 04:30 UTC, merged